namespace NexCode.Marketplace.Sdk;

/// <summary>
/// Spec §18.1 — scaffolds a minimal MCP server project. Two flavours: TypeScript
/// (<c>npm</c>) and Python (<c>uv</c>/<c>pip</c>). Templates are inlined as string
/// constants so the SDK is dependency-free and works in offline environments.
/// </summary>
public sealed record McpServerSpec(
    string Name,
    string Description,
    string Author,
    string Version,
    string[] ToolNames);

public enum McpServerKind
{
    TypeScript,
    Python
}

public sealed class McpServerTemplate
{
    /// <summary>Scaffold the project directory at <paramref name="targetPath"/>.</summary>
    public void Scaffold(string targetPath, McpServerKind kind, McpServerSpec spec)
    {
        ArgumentNullException.ThrowIfNull(targetPath);
        ArgumentNullException.ThrowIfNull(spec);
        if (string.IsNullOrWhiteSpace(spec.Name))
        {
            throw new ArgumentException("Spec name is required.", nameof(spec));
        }

        Directory.CreateDirectory(targetPath);

        switch (kind)
        {
            case McpServerKind.TypeScript:
                ScaffoldTypeScript(targetPath, spec);
                break;
            case McpServerKind.Python:
                ScaffoldPython(targetPath, spec);
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(kind), kind, "Unsupported MCP server kind.");
        }
    }

    private static void ScaffoldTypeScript(string root, McpServerSpec spec)
    {
        File.WriteAllText(Path.Combine(root, "package.json"), TypeScriptPackageJson(spec));
        File.WriteAllText(Path.Combine(root, "tsconfig.json"), TypeScriptTsConfig);
        File.WriteAllText(Path.Combine(root, "README.md"), Readme(spec, "TypeScript"));
        var srcDir = Path.Combine(root, "src");
        Directory.CreateDirectory(srcDir);
        File.WriteAllText(Path.Combine(srcDir, "index.ts"), TypeScriptIndex(spec));
    }

    private static void ScaffoldPython(string root, McpServerSpec spec)
    {
        File.WriteAllText(Path.Combine(root, "pyproject.toml"), PythonPyproject(spec));
        File.WriteAllText(Path.Combine(root, "README.md"), Readme(spec, "Python"));
        var pkgDir = Path.Combine(root, spec.Name.Replace('-', '_'));
        Directory.CreateDirectory(pkgDir);
        File.WriteAllText(Path.Combine(pkgDir, "__init__.py"), "from .server import main\n");
        File.WriteAllText(Path.Combine(pkgDir, "server.py"), PythonServer(spec));
    }

    private static string TypeScriptPackageJson(McpServerSpec spec) =>
        $$"""
        {
          "name": "{{spec.Name}}",
          "version": "{{spec.Version}}",
          "description": "{{spec.Description}}",
          "author": "{{spec.Author}}",
          "type": "module",
          "main": "dist/index.js",
          "bin": { "{{spec.Name}}": "dist/index.js" },
          "scripts": {
            "build": "tsc",
            "start": "node dist/index.js"
          },
          "dependencies": {
            "@modelcontextprotocol/sdk": "^0.5.0"
          },
          "devDependencies": {
            "typescript": "^5.4.0",
            "@types/node": "^20.0.0"
          }
        }
        """;

    private const string TypeScriptTsConfig =
        """
        {
          "compilerOptions": {
            "target": "ES2022",
            "module": "Node16",
            "moduleResolution": "Node16",
            "outDir": "dist",
            "strict": true,
            "esModuleInterop": true
          },
          "include": ["src"]
        }
        """;

    private static string TypeScriptIndex(McpServerSpec spec) =>
        $$"""
        // {{spec.Name}} — generated by NexCode.Marketplace.Sdk.
        // Spec §18.1 reference scaffold. Replace tool stubs with real implementations.
        import { Server } from "@modelcontextprotocol/sdk/server/index.js";
        import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";

        const server = new Server({ name: "{{spec.Name}}", version: "{{spec.Version}}" }, {
          capabilities: { tools: {} }
        });

        const tools = [
        {{string.Join(",\n", spec.ToolNames.Select(t => $"  {{ name: \"{t}\", description: \"TODO: describe {t}\", inputSchema: {{ type: \"object\" }} }}"))}}
        ];

        server.setRequestHandler({ method: "tools/list" } as any, async () => ({ tools }));
        server.setRequestHandler({ method: "tools/call" } as any, async () => ({
          content: [{ type: "text", text: "Not implemented" }]
        }));

        const transport = new StdioServerTransport();
        await server.connect(transport);
        """;

    private static string PythonPyproject(McpServerSpec spec) =>
        $$"""
        [project]
        name = "{{spec.Name}}"
        version = "{{spec.Version}}"
        description = "{{spec.Description}}"
        authors = [{ name = "{{spec.Author}}" }]
        requires-python = ">=3.10"
        dependencies = [
          "mcp>=0.5.0"
        ]

        [project.scripts]
        {{spec.Name.Replace('-', '_')}} = "{{spec.Name.Replace('-', '_')}}.server:main"

        [build-system]
        requires = ["hatchling"]
        build-backend = "hatchling.build"
        """;

    private static string PythonServer(McpServerSpec spec) =>
        $$"""
        # {{spec.Name}} - generated by NexCode.Marketplace.Sdk.
        from mcp.server import Server
        from mcp.server.stdio import stdio_server


        server = Server("{{spec.Name}}")

        TOOLS = [
        {{string.Join(",\n", spec.ToolNames.Select(t => $"    {{\"name\": \"{t}\", \"description\": \"TODO: describe {t}\"}}"))}}
        ]


        @server.list_tools()
        async def list_tools():
            return TOOLS


        @server.call_tool()
        async def call_tool(name: str, arguments: dict):
            return [{"type": "text", "text": "Not implemented"}]


        def main() -> None:
            import asyncio

            async def _run() -> None:
                async with stdio_server() as (read, write):
                    await server.run(read, write, server.create_initialization_options())

            asyncio.run(_run())
        """;

    private static string Readme(McpServerSpec spec, string kind) =>
        $"""
        # {spec.Name}

        {spec.Description}

        Generated by `NexCode.Marketplace.Sdk` ({kind} template).

        ## Tools
        {string.Join("\n", spec.ToolNames.Select(t => $"- `{t}`"))}
        """;
}
