using System.Text.Json;

namespace NexCode.Marketplace.Sdk;

/// <summary>
/// Spec §18.2 — scaffolds a NexCode plugin folder containing
/// <c>nexcode-plugin.json</c>, an <c>index.js</c> entry point, and a README.
/// </summary>
public sealed record PluginTemplateSpec(
    string Id,
    string DisplayName,
    string Description,
    string Author,
    string Version,
    string[] Capabilities);

public sealed class PluginTemplate
{
    public void Scaffold(string targetPath, PluginTemplateSpec spec)
    {
        ArgumentNullException.ThrowIfNull(targetPath);
        ArgumentNullException.ThrowIfNull(spec);
        if (string.IsNullOrWhiteSpace(spec.Id))
        {
            throw new ArgumentException("Plugin id is required.", nameof(spec));
        }

        Directory.CreateDirectory(targetPath);

        var manifest = new
        {
            id = spec.Id,
            name = spec.DisplayName,
            description = spec.Description,
            author = spec.Author,
            version = spec.Version,
            entry = "index.js",
            capabilities = spec.Capabilities
        };

        File.WriteAllText(
            Path.Combine(targetPath, "nexcode-plugin.json"),
            JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true }));

        File.WriteAllText(Path.Combine(targetPath, "index.js"), IndexJs(spec));
        File.WriteAllText(Path.Combine(targetPath, "README.md"), Readme(spec));
    }

    private static string IndexJs(PluginTemplateSpec spec) =>
        $$"""
        // {{spec.Id}} - generated by NexCode.Marketplace.Sdk.
        // Spec §18.2 plugin contract. Replace stubs with real handlers.

        export const manifest = {
          id: "{{spec.Id}}",
          version: "{{spec.Version}}"
        };

        export async function activate(context) {
          context.log?.(`[${manifest.id}] activated`);
          return {
            dispose() {
              context.log?.(`[${manifest.id}] disposed`);
            }
          };
        }
        """;

    private static string Readme(PluginTemplateSpec spec) =>
        $"""
        # {spec.DisplayName}

        {spec.Description}

        Plugin id: `{spec.Id}` (v{spec.Version}) — by {spec.Author}.

        ## Capabilities
        {string.Join("\n", spec.Capabilities.Select(c => $"- `{c}`"))}

        Built with `NexCode.Marketplace.Sdk` per spec §18.
        """;
}
